name: Versioning

on:
  release:
    types: [published, edited]

jobs:
  updateMajorTag:
    name: Update major tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
